spring:
  profiles:
    active: dev

---
spring:
  profile: dev
  application:
    name: order-micro

server:
  port: 7000

---
spring:
  profile: test
  application:
    name: order-micro

server:
  port: 7001
